# version: "3.9"

services:
  mysql_container:
    image: mysql:8.0
    platform: linux/amd64
    container_name: shopapp-mysql
    restart: always
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend_shopapp/database/shopapp.sql:/docker-entrypoint-initdb.d/shopapp.sql
    networks:
      - shopapp_network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -p${MYSQL_ROOT_PASSWORD} --silent",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s

  backend:
    build: ./backend_shopapp
    container_name: shopapp-backend
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    depends_on:
      mysql_container:
        condition: service_healthy
    networks:
      - shopapp_network
    environment:
      RUNNING_IN_DOCKER: "true"
      DB_HOST: mysql_container
      DB_PORT: 3306
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
    volumes:
      - ./backend_shopapp:/app
    command: >
      bash -c "sleep 10 && python -m uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload"

networks:
  shopapp_network:
    driver: bridge

volumes:
  mysql_data:
